name: 'Auto Assign Issues'
on:
  issues:
    types: [opened, reopened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
            teams: issue-reviewers
            numOfAssignee: 1
            allowSelfAssign: false
            repo-token: ${{ secrets.MPARTICLE_BOT }}
