# This is a basic workflow to help you get started with Actions

name: Create Git Issue from Jira

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      jira_ticket:
        type: string
        description: Jira ticket number
        required: true
      ticket_status:
        type: choice
        description: Jira ticket status
        required: true
        options: 
        - To Do
        - In Progress
        - In Review
        - In Validation
        - Blocked
        - Ice Boxed
        - Backlog
        - Done
        - Won't Do
  repository_dispatch:

jobs:
  update-issue-status:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: Login
        uses: atlassian/gajira-login@master

      - name: Get Jira Ticket Links
        uses: fjogeleit/http-request-action@v1.11.0
        with:
          url: ${{ env.JIRA_BASE_URL }}/rest/api/2/issue/${{ github.event.inputs.jira_ticket }}/remotelink
          method: GET
          username: ${{ env.JIRA_USER_EMAIL }}
          password: ${{ env.JIRA_API_TOKEN }}
          customHeaders: '{"Content-Type": "application/json"}'

      # - name: test echo
      #   run: |
      #     echo ${{ env.JIRA_BASE_URL }}/rest/api/2/issue/${{ github.event.inputs.jira_ticket }}/remotelink

      # - name: Get Jira Ticket Links
      #   run: |
      #     curl -k -u ${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_API_TOKEN }} -X GET -H 'Content-Type: application/json' \
      #     ${{ env.JIRA_BASE_URL }}/rest/api/2/issue/${{ github.event.inputs.jira_ticket }}/remotelink
          

