# This is a basic workflow to help you get started with Actions

name: Create Git Issue from Jira

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      jira_ticket:
        type: string
        description: Jira ticket number
        required: true
      ticket_status:
        type: string
        description: Jira ticket status
        required: true
        options: 
        - To Do
        - In Progress
        - In Review
        - In Validation
        - Blocked
        - Ice Boxed
        - Backlog
        - Done
        - Won't Do
  repository_dispatch:


  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a si:ngle job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
