
name: Create Jira Issue

on:
  issues:
    types: ["opened"]

jobs:
  create-issue:
    name: "Create Issue"
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2

      - name: "Login"
        uses: atlassian/gajira-login@master

      - name: "Create"
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: "TP"
          issuetype: "Story"
          summary: |
            ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.body }}
          fields: '{"parent": { "key": "TP-8" }, "Remote Git URL": "www.google.com"}'

      - name: "Log created issue"
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"

      - name: "Create Github comment"
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Tracked internally as ${{ steps.create.outputs.issue }} was created
          reactions: '+1'
          
      - name: Create label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-label'
          label-name: ${{ steps.create.outputs.issue }}
          label-color: '0095b3'
          label-desc: ${{ steps.create.outputs.issue }} 
          
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }} 
          labels: ${{ steps.create.outputs.issue }}    
         
