
name: Create Jira Issue

on:
  issues:
    types: ["opened"]

jobs:
  create-issue:
    name: "Create Issue"
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2

      - name: "Login"
        uses: atlassian/gajira-login@master

      - name: "Create"
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: "TP"
          issuetype: "Story"
          summary: |
            New issue for ${{ github.repository }}
          description: |
            New issue for ${{ github.repository }}

      - name: "Log created issue"
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"

      - name: "Create Github comment"
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Tracked internally as ${{ steps.create.outputs.issue }} was created
          reactions: '+1'
